export default {
    API: '/api',

    VIDEO_UPLOADED: 'VIDEO_UPLOADED',
    TIME_STAMPS_RESEVED: 'TIME_STAMPS_RESEVED',
    SEEK_VIDEO: 'SEEK_VIDEO',
    UPLOADING_STARTED: 'UPLOADING_STARTED',
    VIDEO_UPLOADING_IN_PROGRESS: 'VIDEO_UPLOADING_IN_PROGRESS'
};
