export default {
    API: '/api',

    VIDEO_UPLOADED: 'VIDEO_UPLOADED',
    TIME_STAMPS_RESEVED: 'TIME_STAMPS_RESEVED',
    SEEK_VIDEO: 'SEEK_VIDEO',
    UPLOADING_STARTED: 'UPLOADING_STARTED',
    VIDEO_UPLOADING_IN_PROGRESS: 'VIDEO_UPLOADING_IN_PROGRESS',

    HAVE_NOTHING: 0,
    HAVE_METADATA: 1,
    HAVE_CURRENT_DATA: 2,
    HAVE_FUTURE_DATA: 3,
    HAVE_ENOUGH_DATA: 4
};
